# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.


pipelines:
  default:
    - parallel:
      - step:
          caches:
            - pip
          name: python 3.7
          image: python:3.7.2
          script: # Modify the commands below to build your repository.
            - pip install -e .
            - pytest
      - step:
          caches:
            - pip
          name: python 3.8
          image: python:3.8.1
          script: # Modify the commands below to build your repository.
            - pip install -e .
            - pytest
      - step:
          caches: 
            - pip
          name: deploy docs
          image: python:3.8.1
          script: 
            - git config --global user.email "galen.oneil@nist.gov"
            - git config --global user.name "Bitbucket Pipeline Doc Deploy"
            - pip install -e .
            - pip install recommonmark sphinx
            - apt-get install swig
            - curl -O http://lvserver.ugent.be/xraylib/xraylib-4.0.0.tar.gz
            - gunzip xraylib-4.0.0.tar.gz
            - tar xvf xraylib-4.0.0.tar
            - rm xvf xraylib-4.0.0.tar
            - cd xraylib-4.0.0
            - ./configure --usr/local --disable-fortran2003 --disable-perl
            - make
            - sudo make install
            - cd ..
            - ls /usr/local/lib/python3.8/site-packages
            - rm xraylib-4.0.0
            - cd doc
            - make clean
            - make doctest
            - make html
            - ./deploy_docs_bitbucket.sh $BITBUCKET_BRANCH

