# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.


pipelines:
  default:
    # Feb 21, 2024: our strategy is to test only the oldest and newest python we care about. Save
    # build minutes by skipping any in-between versions. We are using some features in OFF analysis that
    # require python 3.9. Also, as of October 2024, Py 3.8 will be beyond its end-of-life,
    # so for these two reasons, we'll consider 3.9 the oldest supported version.
    #
    # For info about available versions, see https://hub.docker.com/_/python/ and
    # https://support.atlassian.com/bitbucket-cloud/docs/use-docker-images-as-build-environments/.
    # For Python release schedule, see https://www.python.org/downloads/.
    - parallel:
      - step:
          caches:
            - pip
          name: python 3.9
          image: python:3.9
          script: # Modify the commands below to build your repository.
            - pip install --upgrade pip
            - pip install -e .
            - pytest

      - step:
          caches:
            - pip
          name: python 3.12
          image: python:3.12
          script:
            - pip install --upgrade pip
            - pip install -e .
            - pytest
            # Below here: make and deploy documentation.
            - pip install recommonmark sphinx
            - cd doc
            - make clean
            - make doctest
            - make html
            - git config --global user.email "galen.oneil@nist.gov"
            - git config --global user.name "Bitbucket Pipeline Doc Deploy"
            - ./deploy_docs_bitbucket.sh $BITBUCKET_BRANCH
