# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.


pipelines:
  default:
    # Nov 29, 2021: our strategy is to test only the oldest and newest python we care about. Save
    # build minutes by skipping any in-between versions. As of next month, Py 3.6 will be beyond its
    # end-of-life, so we'll consider 3.7 the oldest supported version. Py 3.10 exists, but no MASS
    # developer is using Py 3.10. When that changes (in 2022?), we should begin testing it.
    # For now, stick to 3.9.
    - parallel:
      - step:
          caches:
            - pip
          name: python 3.7
          image: python:3.7.12
          script: # Modify the commands below to build your repository.
            - pip install --upgrade pip
            - pip install -e .
            - pytest
      - step:
          caches:
            - pip
          name: python 3.9
          image: python:3.9.8
          script:
            - git config --global user.email "galen.oneil@nist.gov"
            - git config --global user.name "Bitbucket Pipeline Doc Deploy"
            - pip install --upgrade pip
            - pip install -e .
            - pip install recommonmark sphinx
            - pytest
            # Below here: make and deploy documentation.
            - cd doc
            - make clean
            - make doctest
            - make html
            - ./deploy_docs_bitbucket.sh $BITBUCKET_BRANCH
