"""
test_lines.py

Test that fluorescence line distributions work.

27 April 2017
Joe Fowler
"""
import unittest
import numpy as np
import scipy as sp
import mass


class Test_MnKA_distribution(unittest.TestCase):
    def setUp(self):
        np.random.seed()
        self.distrib = mass.calibration.fluorescence_lines.MnKAlpha()

    def test_for_negative_energies(self):
        """Check that no negative energies are generated by a fluorescence line
        distribution. This tests for issue #112.
        """
        values = self.distrib.rvs(size=100000)
        self.assertLess(0, values.min())

        # This seed definitely caused errors at the time of issue #112.
        np.random.seed(134)
        values = self.distrib.rvs(size=100000)
        self.assertLess(0, values.min())

    def test_quartiles(self):
        """Check that the quartiles of the generated energies are reasonable."""
        values = self.distrib.rvs(size=100000)
        quartiles = sp.stats.scoreatpercentile(values, [25, 50, 75])
        self.assertAlmostEqual(quartiles[0], 5888.3, 0)
        self.assertAlmostEqual(quartiles[1] / 1000, 5896.9 / 1000, 2)
        self.assertAlmostEqual(quartiles[2], 5899.0, 0)


if __name__ == "__main__":
    unittest.main()
