"""
test_lines.py

Test that fluorescence line distributions work.

27 April 2017
Joe Fowler
"""
import unittest
import numpy as np
import mass


class Test_MnKA_distribution(unittest.TestCase):
    def setUp(self):
        self.distrib = mass.calibration.fluorescence_lines.MnKAlphaDistribution()
        np.random.seed(134)

    def test_for_negative(self):
        """Check that no negative energies are generated by a fluorescence line
        distribution. This tests for issue #112.
        """
        values = self.distrib.rvs(size=100000)
        self.assertLess(0, values.min())


if __name__ == "__main__":
    unittest.main()
