# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plot_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(451, 415)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plot = QtWidgets.QWidget(Form)
        self.plot.setObjectName("plot")
        self.verticalLayout.addWidget(self.plot)
        self.widget_2 = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.cb_y_parm = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_y_parm.sizePolicy().hasHeightForWidth())
        self.cb_y_parm.setSizePolicy(sizePolicy)
        self.cb_y_parm.setObjectName("cb_y_parm")
        self.gridLayout.addWidget(self.cb_y_parm, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.cb_x_parm = QtWidgets.QComboBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_x_parm.sizePolicy().hasHeightForWidth())
        self.cb_x_parm.setSizePolicy(sizePolicy)
        self.cb_x_parm.setObjectName("cb_x_parm")
        self.gridLayout.addWidget(self.cb_x_parm, 4, 1, 1, 1)
        self.sb_n_bins = QtWidgets.QSpinBox(self.widget_2)
        self.sb_n_bins.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_n_bins.sizePolicy().hasHeightForWidth())
        self.sb_n_bins.setSizePolicy(sizePolicy)
        self.sb_n_bins.setMaximum(9999)
        self.sb_n_bins.setProperty("value", 100)
        self.sb_n_bins.setObjectName("sb_n_bins")
        self.gridLayout.addWidget(self.sb_n_bins, 4, 6, 1, 1)
        self.le_range_hi = QtWidgets.QLineEdit(self.widget_2)
        self.le_range_hi.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_range_hi.sizePolicy().hasHeightForWidth())
        self.le_range_hi.setSizePolicy(sizePolicy)
        self.le_range_hi.setMaxLength(10)
        self.le_range_hi.setObjectName("le_range_hi")
        self.gridLayout.addWidget(self.le_range_hi, 1, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.cb_histogram = QtWidgets.QCheckBox(self.widget_2)
        self.cb_histogram.setObjectName("cb_histogram")
        self.gridLayout.addWidget(self.cb_histogram, 4, 2, 1, 4)
        self.le_range_lo = QtWidgets.QLineEdit(self.widget_2)
        self.le_range_lo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_range_lo.sizePolicy().hasHeightForWidth())
        self.le_range_lo.setSizePolicy(sizePolicy)
        self.le_range_lo.setMaxLength(10)
        self.le_range_lo.setObjectName("le_range_lo")
        self.gridLayout.addWidget(self.le_range_lo, 1, 4, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.cb_y_parm, self.cb_x_parm)
        Form.setTabOrder(self.cb_x_parm, self.cb_histogram)
        Form.setTabOrder(self.cb_histogram, self.le_range_lo)
        Form.setTabOrder(self.le_range_lo, self.le_range_hi)
        Form.setTabOrder(self.le_range_hi, self.sb_n_bins)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Y"))
        self.label_2.setText(_translate("Form", "X"))
        self.le_range_hi.setText(_translate("Form", "1"))
        self.label.setText(_translate("Form", "Hist Range"))
        self.cb_histogram.setText(_translate("Form", "Histogram"))
        self.le_range_lo.setText(_translate("Form", "0"))

