# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mass/gui/compute_gains_form.ui'
#
# Created: Wed Nov 28 14:20:38 2012
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CreateDataset(object):
    def setupUi(self, CreateDataset):
        CreateDataset.setObjectName(_fromUtf8("CreateDataset"))
        CreateDataset.setWindowModality(QtCore.Qt.ApplicationModal)
        CreateDataset.resize(679, 463)
        self.verticalLayoutWidget_2 = QtGui.QWidget(CreateDataset)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 641, 410))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.file_selection_layout = QtGui.QGridLayout()
        self.file_selection_layout.setObjectName(_fromUtf8("file_selection_layout"))
        self.pulse_file_edit = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse_file_edit.sizePolicy().hasHeightForWidth())
        self.pulse_file_edit.setSizePolicy(sizePolicy)
        self.pulse_file_edit.setMinimumSize(QtCore.QSize(400, 0))
        self.pulse_file_edit.setObjectName(_fromUtf8("pulse_file_edit"))
        self.file_selection_layout.addWidget(self.pulse_file_edit, 0, 0, 1, 1)
        self.choose_pulse_file = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.choose_pulse_file.setEnabled(True)
        self.choose_pulse_file.setFocusPolicy(QtCore.Qt.NoFocus)
        self.choose_pulse_file.setAutoDefault(False)
        self.choose_pulse_file.setObjectName(_fromUtf8("choose_pulse_file"))
        self.file_selection_layout.addWidget(self.choose_pulse_file, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.file_selection_layout)
        self.chan_selection_frame = QtGui.QFrame(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chan_selection_frame.sizePolicy().hasHeightForWidth())
        self.chan_selection_frame.setSizePolicy(sizePolicy)
        self.chan_selection_frame.setMinimumSize(QtCore.QSize(0, 170))
        self.chan_selection_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.chan_selection_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.chan_selection_frame.setObjectName(_fromUtf8("chan_selection_frame"))
        self.gridLayoutWidget = QtGui.QWidget(self.chan_selection_frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 441, 141))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.chan_selection_layout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.chan_selection_layout.setMargin(0)
        self.chan_selection_layout.setObjectName(_fromUtf8("chan_selection_layout"))
        self.chan_selection_label = QtGui.QLabel(self.chan_selection_frame)
        self.chan_selection_label.setEnabled(False)
        self.chan_selection_label.setGeometry(QtCore.QRect(11, 0, 551, 20))
        self.chan_selection_label.setAlignment(QtCore.Qt.AlignCenter)
        self.chan_selection_label.setObjectName(_fromUtf8("chan_selection_label"))
        self.verticalLayoutWidget = QtGui.QWidget(self.chan_selection_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(460, 16, 111, 141))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.chan_selection_controls = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.chan_selection_controls.setContentsMargins(2, -1, 2, -1)
        self.chan_selection_controls.setObjectName(_fromUtf8("chan_selection_controls"))
        self.check_all_chan = QtGui.QPushButton(self.verticalLayoutWidget)
        self.check_all_chan.setEnabled(False)
        self.check_all_chan.setFocusPolicy(QtCore.Qt.NoFocus)
        self.check_all_chan.setObjectName(_fromUtf8("check_all_chan"))
        self.chan_selection_controls.addWidget(self.check_all_chan)
        self.check_default_chan = QtGui.QPushButton(self.verticalLayoutWidget)
        self.check_default_chan.setEnabled(False)
        self.check_default_chan.setObjectName(_fromUtf8("check_default_chan"))
        self.chan_selection_controls.addWidget(self.check_default_chan)
        self.check_no_chan = QtGui.QPushButton(self.verticalLayoutWidget)
        self.check_no_chan.setEnabled(False)
        self.check_no_chan.setFocusPolicy(QtCore.Qt.NoFocus)
        self.check_no_chan.setObjectName(_fromUtf8("check_no_chan"))
        self.chan_selection_controls.addWidget(self.check_no_chan)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.chan_selection_controls.addItem(spacerItem)
        self.verticalLayout.addWidget(self.chan_selection_frame)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(4)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.MaxPulsesLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.MaxPulsesLabel.setObjectName(_fromUtf8("MaxPulsesLabel"))
        self.gridLayout.addWidget(self.MaxPulsesLabel, 0, 0, 1, 1)
        self.MaxPulsesSpin = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.MaxPulsesSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MaxPulsesSpin.setMinimum(-1)
        self.MaxPulsesSpin.setMaximum(999999)
        self.MaxPulsesSpin.setProperty("value", -1)
        self.MaxPulsesSpin.setObjectName(_fromUtf8("MaxPulsesSpin"))
        self.gridLayout.addWidget(self.MaxPulsesSpin, 0, 1, 1, 1)
        self.FilterSamplesLabel = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.FilterSamplesLabel.setEnabled(False)
        self.FilterSamplesLabel.setObjectName(_fromUtf8("FilterSamplesLabel"))
        self.gridLayout.addWidget(self.FilterSamplesLabel, 1, 0, 1, 1)
        self.FilterSamplesSpin = QtGui.QSpinBox(self.verticalLayoutWidget_2)
        self.FilterSamplesSpin.setEnabled(False)
        self.FilterSamplesSpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FilterSamplesSpin.setMinimum(1)
        self.FilterSamplesSpin.setMaximum(9999)
        self.FilterSamplesSpin.setProperty("value", 50)
        self.FilterSamplesSpin.setObjectName(_fromUtf8("FilterSamplesSpin"))
        self.gridLayout.addWidget(self.FilterSamplesSpin, 1, 1, 1, 1)
        self.MaxPulsesLabel_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.MaxPulsesLabel_3.setObjectName(_fromUtf8("MaxPulsesLabel_3"))
        self.gridLayout.addWidget(self.MaxPulsesLabel_3, 2, 0, 1, 1)
        self.LineEnergySpin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.LineEnergySpin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LineEnergySpin.setMaximum(999999999.0)
        self.LineEnergySpin.setObjectName(_fromUtf8("LineEnergySpin"))
        self.gridLayout.addWidget(self.LineEnergySpin, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.OutputFile = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.OutputFile.setObjectName(_fromUtf8("OutputFile"))
        self.gridLayout.addWidget(self.OutputFile, 1, 2, 1, 1)
        self.EnergyMenu = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.EnergyMenu.setEditable(False)
        self.EnergyMenu.setObjectName(_fromUtf8("EnergyMenu"))
        self.EnergyMenu.addItem(_fromUtf8(""))
        self.EnergyMenu.addItem(_fromUtf8(""))
        self.EnergyMenu.addItem(_fromUtf8(""))
        self.EnergyMenu.addItem(_fromUtf8(""))
        self.EnergyMenu.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.EnergyMenu, 3, 0, 1, 2)
        self.gridLayout.setColumnMinimumWidth(0, 120)
        self.gridLayout.setColumnMinimumWidth(1, 120)
        self.verticalLayout.addLayout(self.gridLayout)
        self.take_action = QtGui.QHBoxLayout()
        self.take_action.setContentsMargins(15, -1, 5, -1)
        self.take_action.setObjectName(_fromUtf8("take_action"))
        self.ok_cancel_buttons = QtGui.QDialogButtonBox(self.verticalLayoutWidget_2)
        self.ok_cancel_buttons.setFocusPolicy(QtCore.Qt.TabFocus)
        self.ok_cancel_buttons.setAutoFillBackground(False)
        self.ok_cancel_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.ok_cancel_buttons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.ok_cancel_buttons.setObjectName(_fromUtf8("ok_cancel_buttons"))
        self.take_action.addWidget(self.ok_cancel_buttons)
        self.verticalLayout.addLayout(self.take_action)

        self.retranslateUi(CreateDataset)
        QtCore.QObject.connect(self.ok_cancel_buttons, QtCore.SIGNAL(_fromUtf8("accepted()")), CreateDataset.accept)
        QtCore.QObject.connect(self.ok_cancel_buttons, QtCore.SIGNAL(_fromUtf8("rejected()")), CreateDataset.reject)
        QtCore.QObject.connect(self.pulse_file_edit, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), CreateDataset.file_template_textEdited)
        QtCore.QObject.connect(self.EnergyMenu, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), CreateDataset.energy_menu_chooser)
        QtCore.QObject.connect(self.OutputFile, QtCore.SIGNAL(_fromUtf8("editingFinished()")), CreateDataset.output_file_textEdited)
        QtCore.QMetaObject.connectSlotsByName(CreateDataset)
        CreateDataset.setTabOrder(self.pulse_file_edit, self.choose_pulse_file)
        CreateDataset.setTabOrder(self.choose_pulse_file, self.check_all_chan)
        CreateDataset.setTabOrder(self.check_all_chan, self.check_default_chan)
        CreateDataset.setTabOrder(self.check_default_chan, self.check_no_chan)
        CreateDataset.setTabOrder(self.check_no_chan, self.ok_cancel_buttons)

    def retranslateUi(self, CreateDataset):
        CreateDataset.setWindowTitle(QtGui.QApplication.translate("CreateDataset", "Compute TES Gains for a Single Bright Line", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("CreateDataset", "Whether to load indicated pulse files", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CreateDataset", "Select one example file for pulse and/or noise data:", None, QtGui.QApplication.UnicodeUTF8))
        self.choose_pulse_file.setToolTip(QtGui.QApplication.translate("CreateDataset", "Choose the template pulse file name.", None, QtGui.QApplication.UnicodeUTF8))
        self.choose_pulse_file.setText(QtGui.QApplication.translate("CreateDataset", "choose", None, QtGui.QApplication.UnicodeUTF8))
        self.chan_selection_label.setText(QtGui.QApplication.translate("CreateDataset", "Choose channels to load", None, QtGui.QApplication.UnicodeUTF8))
        self.check_all_chan.setToolTip(QtGui.QApplication.translate("CreateDataset", "Select all channels on disk", None, QtGui.QApplication.UnicodeUTF8))
        self.check_all_chan.setText(QtGui.QApplication.translate("CreateDataset", "All chan", None, QtGui.QApplication.UnicodeUTF8))
        self.check_default_chan.setToolTip(QtGui.QApplication.translate("CreateDataset", "Select all channels but the disabled ones.", None, QtGui.QApplication.UnicodeUTF8))
        self.check_default_chan.setText(QtGui.QApplication.translate("CreateDataset", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.check_no_chan.setToolTip(QtGui.QApplication.translate("CreateDataset", "Unselect all channels", None, QtGui.QApplication.UnicodeUTF8))
        self.check_no_chan.setText(QtGui.QApplication.translate("CreateDataset", "No chan", None, QtGui.QApplication.UnicodeUTF8))
        self.MaxPulsesLabel.setText(QtGui.QApplication.translate("CreateDataset", "Max Pulses", None, QtGui.QApplication.UnicodeUTF8))
        self.MaxPulsesSpin.setToolTip(QtGui.QApplication.translate("CreateDataset", "Analyze only this many pulses (-1 means ALL)", None, QtGui.QApplication.UnicodeUTF8))
        self.FilterSamplesLabel.setText(QtGui.QApplication.translate("CreateDataset", "Filter smp(NOT DONE)", None, QtGui.QApplication.UnicodeUTF8))
        self.FilterSamplesSpin.setToolTip(QtGui.QApplication.translate("CreateDataset", "Sub-optimal filter uses this many samples starting at trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.MaxPulsesLabel_3.setText(QtGui.QApplication.translate("CreateDataset", "Line Energy (eV)", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEnergySpin.setToolTip(QtGui.QApplication.translate("CreateDataset", "Spectral line location in eV (0.00 means rescale raw units to their median)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CreateDataset", "Output File", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputFile.setText(QtGui.QApplication.translate("CreateDataset", "./detector_gains.cfg", None, QtGui.QApplication.UnicodeUTF8))
        self.EnergyMenu.setItemText(0, QtGui.QApplication.translate("CreateDataset", "(choose standard lines here)", None, QtGui.QApplication.UnicodeUTF8))
        self.EnergyMenu.setItemText(1, QtGui.QApplication.translate("CreateDataset", "Mn Kalpha (5986 eV)", None, QtGui.QApplication.UnicodeUTF8))
        self.EnergyMenu.setItemText(2, QtGui.QApplication.translate("CreateDataset", "Carbon Kalpha (277 eV)", None, QtGui.QApplication.UnicodeUTF8))
        self.EnergyMenu.setItemText(3, QtGui.QApplication.translate("CreateDataset", "Oxygen Kalpha (524.9 eV)", None, QtGui.QApplication.UnicodeUTF8))
        self.EnergyMenu.setItemText(4, QtGui.QApplication.translate("CreateDataset", "153Gd (97.143 keV)", None, QtGui.QApplication.UnicodeUTF8))

