# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mass/gui/load_data_dialog_form.ui'
#
# Created: Fri Apr 20 10:43:10 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CreateDataset(object):
    def setupUi(self, CreateDataset):
        CreateDataset.setObjectName(_fromUtf8("CreateDataset"))
        CreateDataset.setWindowModality(QtCore.Qt.ApplicationModal)
        CreateDataset.resize(596, 336)
        self.horizontalLayoutWidget = QtGui.QWidget(CreateDataset)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 280, 571, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.take_action = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.take_action.setContentsMargins(15, -1, 5, -1)
        self.take_action.setObjectName(_fromUtf8("take_action"))
        self.summarize_on_load = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.summarize_on_load.setObjectName(_fromUtf8("summarize_on_load"))
        self.take_action.addWidget(self.summarize_on_load)
        self.ok_cancel_buttons = QtGui.QDialogButtonBox(self.horizontalLayoutWidget)
        self.ok_cancel_buttons.setFocusPolicy(QtCore.Qt.TabFocus)
        self.ok_cancel_buttons.setAutoFillBackground(False)
        self.ok_cancel_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.ok_cancel_buttons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.ok_cancel_buttons.setObjectName(_fromUtf8("ok_cancel_buttons"))
        self.take_action.addWidget(self.ok_cancel_buttons)
        self.label = QtGui.QLabel(CreateDataset)
        self.label.setGeometry(QtCore.QRect(10, 10, 571, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.chan_selection_frame = QtGui.QFrame(CreateDataset)
        self.chan_selection_frame.setGeometry(QtCore.QRect(10, 110, 571, 151))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chan_selection_frame.sizePolicy().hasHeightForWidth())
        self.chan_selection_frame.setSizePolicy(sizePolicy)
        self.chan_selection_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.chan_selection_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.chan_selection_frame.setObjectName(_fromUtf8("chan_selection_frame"))
        self.gridLayoutWidget = QtGui.QWidget(self.chan_selection_frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 441, 121))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.chan_selection_layout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.chan_selection_layout.setMargin(0)
        self.chan_selection_layout.setObjectName(_fromUtf8("chan_selection_layout"))
        self.chan_selection_label = QtGui.QLabel(self.chan_selection_frame)
        self.chan_selection_label.setEnabled(False)
        self.chan_selection_label.setGeometry(QtCore.QRect(11, 0, 551, 20))
        self.chan_selection_label.setAlignment(QtCore.Qt.AlignCenter)
        self.chan_selection_label.setObjectName(_fromUtf8("chan_selection_label"))
        self.verticalLayoutWidget = QtGui.QWidget(self.chan_selection_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(460, 40, 111, 81))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.chan_selection_controls = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.chan_selection_controls.setContentsMargins(2, -1, 2, -1)
        self.chan_selection_controls.setObjectName(_fromUtf8("chan_selection_controls"))
        self.check_all_chan = QtGui.QPushButton(self.verticalLayoutWidget)
        self.check_all_chan.setEnabled(False)
        self.check_all_chan.setObjectName(_fromUtf8("check_all_chan"))
        self.chan_selection_controls.addWidget(self.check_all_chan)
        self.check_default_chan = QtGui.QPushButton(self.verticalLayoutWidget)
        self.check_default_chan.setEnabled(False)
        self.check_default_chan.setObjectName(_fromUtf8("check_default_chan"))
        self.chan_selection_controls.addWidget(self.check_default_chan)
        self.check_no_chan = QtGui.QPushButton(self.verticalLayoutWidget)
        self.check_no_chan.setEnabled(False)
        self.check_no_chan.setObjectName(_fromUtf8("check_no_chan"))
        self.chan_selection_controls.addWidget(self.check_no_chan)
        self.widget = QtGui.QWidget(CreateDataset)
        self.widget.setGeometry(QtCore.QRect(10, 30, 571, 71))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.file_selection_layout = QtGui.QGridLayout(self.widget)
        self.file_selection_layout.setMargin(0)
        self.file_selection_layout.setObjectName(_fromUtf8("file_selection_layout"))
        self.pulse_file_edit = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulse_file_edit.sizePolicy().hasHeightForWidth())
        self.pulse_file_edit.setSizePolicy(sizePolicy)
        self.pulse_file_edit.setMinimumSize(QtCore.QSize(400, 0))
        self.pulse_file_edit.setObjectName(_fromUtf8("pulse_file_edit"))
        self.file_selection_layout.addWidget(self.pulse_file_edit, 0, 1, 1, 1)
        self.use_pulses = QtGui.QCheckBox(self.widget)
        self.use_pulses.setChecked(False)
        self.use_pulses.setTristate(False)
        self.use_pulses.setObjectName(_fromUtf8("use_pulses"))
        self.file_selection_layout.addWidget(self.use_pulses, 0, 0, 1, 1)
        self.use_noise = QtGui.QCheckBox(self.widget)
        self.use_noise.setChecked(False)
        self.use_noise.setTristate(False)
        self.use_noise.setObjectName(_fromUtf8("use_noise"))
        self.file_selection_layout.addWidget(self.use_noise, 4, 0, 1, 1)
        self.noise_file_edit = QtGui.QLineEdit(self.widget)
        self.noise_file_edit.setMinimumSize(QtCore.QSize(400, 0))
        self.noise_file_edit.setObjectName(_fromUtf8("noise_file_edit"))
        self.file_selection_layout.addWidget(self.noise_file_edit, 4, 1, 1, 1)
        self.choose_pulse_file = QtGui.QPushButton(self.widget)
        self.choose_pulse_file.setEnabled(True)
        self.choose_pulse_file.setAutoDefault(False)
        self.choose_pulse_file.setObjectName(_fromUtf8("choose_pulse_file"))
        self.file_selection_layout.addWidget(self.choose_pulse_file, 0, 2, 1, 1)
        self.choose_noise_file = QtGui.QPushButton(self.widget)
        self.choose_noise_file.setEnabled(True)
        self.choose_noise_file.setAutoDefault(False)
        self.choose_noise_file.setObjectName(_fromUtf8("choose_noise_file"))
        self.file_selection_layout.addWidget(self.choose_noise_file, 4, 2, 1, 1)
        self.file_selection_layout.setColumnStretch(1, 1)

        self.retranslateUi(CreateDataset)
        QtCore.QObject.connect(self.ok_cancel_buttons, QtCore.SIGNAL(_fromUtf8("accepted()")), CreateDataset.accept)
        QtCore.QObject.connect(self.ok_cancel_buttons, QtCore.SIGNAL(_fromUtf8("rejected()")), CreateDataset.reject)
        QtCore.QMetaObject.connectSlotsByName(CreateDataset)
        CreateDataset.setTabOrder(self.use_pulses, self.pulse_file_edit)
        CreateDataset.setTabOrder(self.pulse_file_edit, self.choose_pulse_file)
        CreateDataset.setTabOrder(self.choose_pulse_file, self.use_noise)
        CreateDataset.setTabOrder(self.use_noise, self.noise_file_edit)
        CreateDataset.setTabOrder(self.noise_file_edit, self.choose_noise_file)
        CreateDataset.setTabOrder(self.choose_noise_file, self.check_all_chan)
        CreateDataset.setTabOrder(self.check_all_chan, self.check_default_chan)
        CreateDataset.setTabOrder(self.check_default_chan, self.check_no_chan)
        CreateDataset.setTabOrder(self.check_no_chan, self.summarize_on_load)
        CreateDataset.setTabOrder(self.summarize_on_load, self.ok_cancel_buttons)

    def retranslateUi(self, CreateDataset):
        CreateDataset.setWindowTitle(QtGui.QApplication.translate("CreateDataset", "Mass: Load Data", None, QtGui.QApplication.UnicodeUTF8))
        self.summarize_on_load.setToolTip(QtGui.QApplication.translate("CreateDataset", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Whether to run method <span style=\" font-style:italic;\">summarize_data</span>() on dataset </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">before returning it.  (Can be convenient but slower.)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.summarize_on_load.setText(QtGui.QApplication.translate("CreateDataset", "Summarize on load", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("CreateDataset", "Whether to load indicated pulse files", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CreateDataset", "Select one example file for pulse and/or noise data:", None, QtGui.QApplication.UnicodeUTF8))
        self.chan_selection_label.setText(QtGui.QApplication.translate("CreateDataset", "Choose channels to load", None, QtGui.QApplication.UnicodeUTF8))
        self.check_all_chan.setToolTip(QtGui.QApplication.translate("CreateDataset", "Select all channels on disk", None, QtGui.QApplication.UnicodeUTF8))
        self.check_all_chan.setText(QtGui.QApplication.translate("CreateDataset", "All chan", None, QtGui.QApplication.UnicodeUTF8))
        self.check_default_chan.setToolTip(QtGui.QApplication.translate("CreateDataset", "Select all channels but the disabled ones.", None, QtGui.QApplication.UnicodeUTF8))
        self.check_default_chan.setText(QtGui.QApplication.translate("CreateDataset", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.check_no_chan.setToolTip(QtGui.QApplication.translate("CreateDataset", "Unselect all channels", None, QtGui.QApplication.UnicodeUTF8))
        self.check_no_chan.setText(QtGui.QApplication.translate("CreateDataset", "No chan", None, QtGui.QApplication.UnicodeUTF8))
        self.use_pulses.setToolTip(QtGui.QApplication.translate("CreateDataset", "Whether to load indicated pulse files.", None, QtGui.QApplication.UnicodeUTF8))
        self.use_pulses.setText(QtGui.QApplication.translate("CreateDataset", "Pulses", None, QtGui.QApplication.UnicodeUTF8))
        self.use_noise.setToolTip(QtGui.QApplication.translate("CreateDataset", "Whether to load indicated noise files", None, QtGui.QApplication.UnicodeUTF8))
        self.use_noise.setText(QtGui.QApplication.translate("CreateDataset", "Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.choose_pulse_file.setToolTip(QtGui.QApplication.translate("CreateDataset", "Choose the template pulse file name.", None, QtGui.QApplication.UnicodeUTF8))
        self.choose_pulse_file.setText(QtGui.QApplication.translate("CreateDataset", "choose", None, QtGui.QApplication.UnicodeUTF8))
        self.choose_noise_file.setToolTip(QtGui.QApplication.translate("CreateDataset", "Choose the template pulse file name.", None, QtGui.QApplication.UnicodeUTF8))
        self.choose_noise_file.setText(QtGui.QApplication.translate("CreateDataset", "choose", None, QtGui.QApplication.UnicodeUTF8))

