# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mass/gui/make_cuts_dialog_form.ui'
#
# Created: Wed May  9 16:16:28 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1253, 837)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1200, 800))
        Dialog.setSizeGripEnabled(True)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setMargin(4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.control_verticalLayout = QtGui.QVBoxLayout()
        self.control_verticalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.control_verticalLayout.setObjectName(_fromUtf8("control_verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 6, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.control_verticalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.control_verticalLayout.addWidget(self.label)
        self.parameter_chooser = QtGui.QComboBox(Dialog)
        self.parameter_chooser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.parameter_chooser.setObjectName(_fromUtf8("parameter_chooser"))
        self.parameter_chooser.addItem(_fromUtf8(""))
        self.parameter_chooser.addItem(_fromUtf8(""))
        self.parameter_chooser.addItem(_fromUtf8(""))
        self.parameter_chooser.addItem(_fromUtf8(""))
        self.parameter_chooser.addItem(_fromUtf8(""))
        self.parameter_chooser.addItem(_fromUtf8(""))
        self.parameter_chooser.addItem(_fromUtf8(""))
        self.control_verticalLayout.addWidget(self.parameter_chooser)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.control_verticalLayout.addWidget(self.label_2)
        self.num_channel_chooser = QtGui.QComboBox(Dialog)
        self.num_channel_chooser.setEnabled(True)
        self.num_channel_chooser.setFocusPolicy(QtCore.Qt.TabFocus)
        self.num_channel_chooser.setObjectName(_fromUtf8("num_channel_chooser"))
        self.num_channel_chooser.addItem(_fromUtf8(""))
        self.num_channel_chooser.addItem(_fromUtf8(""))
        self.num_channel_chooser.addItem(_fromUtf8(""))
        self.num_channel_chooser.addItem(_fromUtf8(""))
        self.num_channel_chooser.addItem(_fromUtf8(""))
        self.num_channel_chooser.addItem(_fromUtf8(""))
        self.num_channel_chooser.addItem(_fromUtf8(""))
        self.control_verticalLayout.addWidget(self.num_channel_chooser)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.control_verticalLayout.addWidget(self.label_3)
        self.dataset_chooser = QtGui.QComboBox(Dialog)
        self.dataset_chooser.setEnabled(True)
        self.dataset_chooser.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.dataset_chooser.setObjectName(_fromUtf8("dataset_chooser"))
        self.dataset_chooser.addItem(_fromUtf8(""))
        self.control_verticalLayout.addWidget(self.dataset_chooser)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.control_verticalLayout.addItem(spacerItem1)
        self.replot_button = QtGui.QPushButton(Dialog)
        self.replot_button.setObjectName(_fromUtf8("replot_button"))
        self.control_verticalLayout.addWidget(self.replot_button)
        self.cuts_limits_layout = QtGui.QVBoxLayout()
        self.cuts_limits_layout.setObjectName(_fromUtf8("cuts_limits_layout"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cuts_limits_layout.addWidget(self.label_4)
        self.cuts_gridLayout = QtGui.QGridLayout()
        self.cuts_gridLayout.setObjectName(_fromUtf8("cuts_gridLayout"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cuts_gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.cuts_min_spin = QtGui.QDoubleSpinBox(Dialog)
        self.cuts_min_spin.setDecimals(3)
        self.cuts_min_spin.setMinimum(-99.0)
        self.cuts_min_spin.setMaximum(999.999)
        self.cuts_min_spin.setProperty("value", 0.0)
        self.cuts_min_spin.setObjectName(_fromUtf8("cuts_min_spin"))
        self.cuts_gridLayout.addWidget(self.cuts_min_spin, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cuts_gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.cuts_max_spin = QtGui.QDoubleSpinBox(Dialog)
        self.cuts_max_spin.setDecimals(3)
        self.cuts_max_spin.setMaximum(999.999)
        self.cuts_max_spin.setObjectName(_fromUtf8("cuts_max_spin"))
        self.cuts_gridLayout.addWidget(self.cuts_max_spin, 1, 1, 1, 1)
        self.use_min_cut = QtGui.QCheckBox(Dialog)
        self.use_min_cut.setObjectName(_fromUtf8("use_min_cut"))
        self.cuts_gridLayout.addWidget(self.use_min_cut, 0, 2, 1, 1)
        self.use_max_cut = QtGui.QCheckBox(Dialog)
        self.use_max_cut.setObjectName(_fromUtf8("use_max_cut"))
        self.cuts_gridLayout.addWidget(self.use_max_cut, 1, 2, 1, 1)
        self.cuts_limits_layout.addLayout(self.cuts_gridLayout)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.cuts_limits_layout.addWidget(self.label_9)
        self.hist_limits_gridLayout = QtGui.QGridLayout()
        self.hist_limits_gridLayout.setObjectName(_fromUtf8("hist_limits_gridLayout"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.hist_limits_gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.hist_limits_gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.use_hist_min = QtGui.QCheckBox(Dialog)
        self.use_hist_min.setObjectName(_fromUtf8("use_hist_min"))
        self.hist_limits_gridLayout.addWidget(self.use_hist_min, 0, 2, 1, 1)
        self.use_hist_max = QtGui.QCheckBox(Dialog)
        self.use_hist_max.setObjectName(_fromUtf8("use_hist_max"))
        self.hist_limits_gridLayout.addWidget(self.use_hist_max, 1, 2, 1, 1)
        self.hist_max_spin = QtGui.QDoubleSpinBox(Dialog)
        self.hist_max_spin.setEnabled(False)
        self.hist_max_spin.setDecimals(3)
        self.hist_max_spin.setMaximum(9999.999)
        self.hist_max_spin.setObjectName(_fromUtf8("hist_max_spin"))
        self.hist_limits_gridLayout.addWidget(self.hist_max_spin, 1, 1, 1, 1)
        self.hist_min_spin = QtGui.QDoubleSpinBox(Dialog)
        self.hist_min_spin.setEnabled(False)
        self.hist_min_spin.setDecimals(3)
        self.hist_min_spin.setMinimum(-99.0)
        self.hist_min_spin.setMaximum(999.999)
        self.hist_min_spin.setObjectName(_fromUtf8("hist_min_spin"))
        self.hist_limits_gridLayout.addWidget(self.hist_min_spin, 0, 1, 1, 1)
        self.cuts_limits_layout.addLayout(self.hist_limits_gridLayout)
        self.control_verticalLayout.addLayout(self.cuts_limits_layout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.apply_cuts = QtGui.QPushButton(Dialog)
        self.apply_cuts.setObjectName(_fromUtf8("apply_cuts"))
        self.horizontalLayout_3.addWidget(self.apply_cuts)
        self.clear_cuts = QtGui.QPushButton(Dialog)
        self.clear_cuts.setObjectName(_fromUtf8("clear_cuts"))
        self.horizontalLayout_3.addWidget(self.clear_cuts)
        self.control_verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.control_verticalLayout.addItem(spacerItem2)
        self.apply_cuts_check = QtGui.QCheckBox(Dialog)
        self.apply_cuts_check.setChecked(True)
        self.apply_cuts_check.setObjectName(_fromUtf8("apply_cuts_check"))
        self.control_verticalLayout.addWidget(self.apply_cuts_check)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dialog_control_buttons = QtGui.QDialogButtonBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dialog_control_buttons.sizePolicy().hasHeightForWidth())
        self.dialog_control_buttons.setSizePolicy(sizePolicy)
        self.dialog_control_buttons.setOrientation(QtCore.Qt.Vertical)
        self.dialog_control_buttons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.dialog_control_buttons.setObjectName(_fromUtf8("dialog_control_buttons"))
        self.horizontalLayout.addWidget(self.dialog_control_buttons)
        self.control_verticalLayout.addLayout(self.horizontalLayout)
        self.control_verticalLayout.setStretch(11, 1)
        self.horizontalLayout_2.addLayout(self.control_verticalLayout)
        self.pylab_holder = QtGui.QFrame(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pylab_holder.sizePolicy().hasHeightForWidth())
        self.pylab_holder.setSizePolicy(sizePolicy)
        self.pylab_holder.setMinimumSize(QtCore.QSize(1024, 800))
        self.pylab_holder.setFrameShape(QtGui.QFrame.StyledPanel)
        self.pylab_holder.setFrameShadow(QtGui.QFrame.Raised)
        self.pylab_holder.setObjectName(_fromUtf8("pylab_holder"))
        self.horizontalLayout_2.addWidget(self.pylab_holder)
        self.label.setBuddy(self.parameter_chooser)
        self.label_2.setBuddy(self.num_channel_chooser)
        self.label_3.setBuddy(self.dataset_chooser)
        self.label_5.setBuddy(self.cuts_min_spin)
        self.label_6.setBuddy(self.cuts_max_spin)
        self.label_8.setBuddy(self.hist_max_spin)
        self.label_7.setBuddy(self.hist_min_spin)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.dialog_control_buttons, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.dialog_control_buttons, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.parameter_chooser, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.changed_parameter_number)
        QtCore.QObject.connect(self.cuts_max_spin, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Dialog.changed_cut_parameter)
        QtCore.QObject.connect(self.cuts_min_spin, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), Dialog.changed_cut_parameter)
        QtCore.QObject.connect(self.use_min_cut, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cuts_min_spin.setEnabled)
        QtCore.QObject.connect(self.use_max_cut, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.cuts_max_spin.setEnabled)
        QtCore.QObject.connect(self.use_hist_max, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.hist_max_spin.setEnabled)
        QtCore.QObject.connect(self.use_hist_min, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.hist_min_spin.setEnabled)
        QtCore.QObject.connect(self.replot_button, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.update_plots)
        QtCore.QObject.connect(self.dataset_chooser, QtCore.SIGNAL(_fromUtf8("activated(QString)")), Dialog.update_plots)
        QtCore.QObject.connect(self.num_channel_chooser, QtCore.SIGNAL(_fromUtf8("activated(QString)")), Dialog.changed_dataset_count)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.parameter_chooser, self.num_channel_chooser)
        Dialog.setTabOrder(self.num_channel_chooser, self.dataset_chooser)
        Dialog.setTabOrder(self.dataset_chooser, self.replot_button)
        Dialog.setTabOrder(self.replot_button, self.cuts_min_spin)
        Dialog.setTabOrder(self.cuts_min_spin, self.use_min_cut)
        Dialog.setTabOrder(self.use_min_cut, self.cuts_max_spin)
        Dialog.setTabOrder(self.cuts_max_spin, self.use_max_cut)
        Dialog.setTabOrder(self.use_max_cut, self.hist_min_spin)
        Dialog.setTabOrder(self.hist_min_spin, self.use_hist_min)
        Dialog.setTabOrder(self.use_hist_min, self.hist_max_spin)
        Dialog.setTabOrder(self.hist_max_spin, self.use_hist_max)
        Dialog.setTabOrder(self.use_hist_max, self.apply_cuts_check)
        Dialog.setTabOrder(self.apply_cuts_check, self.dialog_control_buttons)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Parameter to view", None, QtGui.QApplication.UnicodeUTF8))
        self.parameter_chooser.setItemText(0, QtGui.QApplication.translate("Dialog", "0: Pulse Avg", None, QtGui.QApplication.UnicodeUTF8))
        self.parameter_chooser.setItemText(1, QtGui.QApplication.translate("Dialog", "1: Pretrig RMS", None, QtGui.QApplication.UnicodeUTF8))
        self.parameter_chooser.setItemText(2, QtGui.QApplication.translate("Dialog", "2: Pretrig Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.parameter_chooser.setItemText(3, QtGui.QApplication.translate("Dialog", "3: Peak Value", None, QtGui.QApplication.UnicodeUTF8))
        self.parameter_chooser.setItemText(4, QtGui.QApplication.translate("Dialog", "4: Max Posttrig dp/dt", None, QtGui.QApplication.UnicodeUTF8))
        self.parameter_chooser.setItemText(5, QtGui.QApplication.translate("Dialog", "5: Rise Time (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.parameter_chooser.setItemText(6, QtGui.QApplication.translate("Dialog", "6: Peak Time (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Channels at a time", None, QtGui.QApplication.UnicodeUTF8))
        self.num_channel_chooser.setItemText(0, QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.num_channel_chooser.setItemText(1, QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.num_channel_chooser.setItemText(2, QtGui.QApplication.translate("Dialog", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.num_channel_chooser.setItemText(3, QtGui.QApplication.translate("Dialog", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.num_channel_chooser.setItemText(4, QtGui.QApplication.translate("Dialog", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.num_channel_chooser.setItemText(5, QtGui.QApplication.translate("Dialog", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.num_channel_chooser.setItemText(6, QtGui.QApplication.translate("Dialog", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Datasets", None, QtGui.QApplication.UnicodeUTF8))
        self.dataset_chooser.setItemText(0, QtGui.QApplication.translate("Dialog", "0-3", None, QtGui.QApplication.UnicodeUTF8))
        self.replot_button.setText(QtGui.QApplication.translate("Dialog", "Replot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Cuts", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.use_min_cut.setText(QtGui.QApplication.translate("Dialog", "Use", None, QtGui.QApplication.UnicodeUTF8))
        self.use_max_cut.setText(QtGui.QApplication.translate("Dialog", "Use", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Histogram limits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.use_hist_min.setToolTip(QtGui.QApplication.translate("Dialog", "Do we fix the histogram lower limit?", None, QtGui.QApplication.UnicodeUTF8))
        self.use_hist_min.setText(QtGui.QApplication.translate("Dialog", "Use", None, QtGui.QApplication.UnicodeUTF8))
        self.use_hist_max.setToolTip(QtGui.QApplication.translate("Dialog", "Do we fix the histogram lower limit?", None, QtGui.QApplication.UnicodeUTF8))
        self.use_hist_max.setText(QtGui.QApplication.translate("Dialog", "Use", None, QtGui.QApplication.UnicodeUTF8))
        self.hist_max_spin.setToolTip(QtGui.QApplication.translate("Dialog", "Lower limit of the histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.hist_min_spin.setToolTip(QtGui.QApplication.translate("Dialog", "Upper limit of the histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.apply_cuts.setText(QtGui.QApplication.translate("Dialog", "Apply Cuts", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_cuts.setText(QtGui.QApplication.translate("Dialog", "Clear Cuts", None, QtGui.QApplication.UnicodeUTF8))
        self.apply_cuts_check.setToolTip(QtGui.QApplication.translate("Dialog", "Whether to apply cuts before returning", None, QtGui.QApplication.UnicodeUTF8))
        self.apply_cuts_check.setText(QtGui.QApplication.translate("Dialog", "Apply cuts on OK?", None, QtGui.QApplication.UnicodeUTF8))
        self.pylab_holder.setToolTip(QtGui.QApplication.translate("Dialog", "Plotting window", None, QtGui.QApplication.UnicodeUTF8))

